function onUpdate()
if curStep <= 0 then
makeLuaSprite('black', '', 0, 0);
makeGraphic('black',1280,720,'000000')	
setProperty('black.scale.x',999)
setProperty('black.scale.y',999)
addLuaSprite('black', false);

makeLuaSprite('sky','weeb/school/weebSky',0,0)
scaleObject('sky',6,6)
setProperty('sky.antialiasing',false)
setScrollFactor('sky',0.1,0.1)
addLuaSprite('sky')

makeLuaSprite('skyg','weeb/school/weebSkyGlitch',0,0)
scaleObject('skyg',6,6)
setProperty('skyg.antialiasing',false)
setProperty('skyg.visible',false)
setScrollFactor('skyg',0.1,0.1)
addLuaSprite('skyg')

makeLuaSprite('school','weeb/school/weebSchool',-200,0)
scaleObject('school',6,6)
setProperty('school.antialiasing',false)
setScrollFactor('school',0.6,0.9)
addLuaSprite('school')

makeLuaSprite('schoolg','weeb/school/weebSchoolGlitch',-200,0)
scaleObject('schoolg',6,6)
setProperty('schoolg.antialiasing',false)
setProperty('schoolg.visible',false)
setScrollFactor('schoolg',0.6,0.9)
addLuaSprite('schoolg')

makeLuaSprite('schoolg2','weeb/school/scarySchool/weebSchoolEvil',-200,0)
scaleObject('schoolg2',6,6)
setProperty('schoolg2.antialiasing',false)
setProperty('schoolg2.visible',false)
setScrollFactor('schoolg2',0.6,0.9)
addLuaSprite('schoolg2')

makeLuaSprite('street','weeb/school/weebStreet',-200,0)
scaleObject('street',6,6)
setProperty('street.antialiasing',false)
setScrollFactor('street',0.95,0.95)
addLuaSprite('street')

makeLuaSprite('streetg','weeb/school/weebStreetGlitch',-200,0)
scaleObject('streetg',6,6)
setProperty('streetg.antialiasing',false)
setScrollFactor('streetg',0.95,0.95)
setProperty('streetg.visible',false)
addLuaSprite('streetg')

makeLuaSprite('streetg2','weeb/school/scarySchool/weebStreetEvil',-200,0)
scaleObject('streetg2',6,6)
setProperty('streetg2.antialiasing',false)
setScrollFactor('streetg2',0.95,0.95)
setProperty('streetg2.visible',false)
addLuaSprite('streetg2')

makeLuaSprite('bgtree','weeb/school/weebTreesBack',-150,50)
scaleObject('bgtree',5.5,5.5)
setProperty('bgtree.antialiasing',false)
setScrollFactor('bgtree',0.9,0.9)
addLuaSprite('bgtree')

makeLuaSprite('bgtreeg','weeb/school/weebTreesBackGlitch',-150,50)
scaleObject('bgtreeg',5.5,5.5)
setProperty('bgtreeg.antialiasing',false)
setScrollFactor('bgtreeg',0.9,0.9)
setProperty('bgtreeg.visible',false)
addLuaSprite('bgtreeg')

makeLuaSprite('bgtreeg2','weeb/school/scarySchool/weebTreesBackEvil',-150,50)
scaleObject('bgtreeg2',5.5,5.5)
setProperty('bgtreeg2.antialiasing',false)
setScrollFactor('bgtreeg2',0.9,0.9)
setProperty('bgtreeg2.visible',false)
addLuaSprite('bgtreeg2')

makeAnimatedLuaSprite('trees','weeb/school/weebTrees',-780,-1000)
addAnimationByPrefix('trees','idle','trees',12,true)
scaleObject('trees',6,6)
setScrollFactor('trees',0.85,0.85)
setProperty('trees.antialiasing',false)
addLuaSprite('trees')

makeAnimatedLuaSprite('treesg','weeb/school/weebTreesGlitch',-780,-1000)
addAnimationByPrefix('treesg','idle','trees',12,true)
scaleObject('treesg',6,6)
setScrollFactor('treesg',0.85,0.85)
setProperty('treesg.antialiasing',false)
setProperty('treesg.visible',false)
addLuaSprite('treesg')

makeAnimatedLuaSprite('treesg2','weeb/school/scarySchool/weebTreesEvil',-780,-1000)
addAnimationByPrefix('treesg2','idle','trees',12,true)
scaleObject('treesg2',6,6)
setScrollFactor('treesg2',0.85,0.85)
setProperty('treesg2.antialiasing',false)
setProperty('treesg2.visible',false)
addLuaSprite('treesg2')

makeAnimatedLuaSprite('petals','weeb/school/petals',-200,-40)
addAnimationByPrefix('petals','idle','PETALS ALL',24,true)
scaleObject('petals',6,6)
setScrollFactor('petals',0.85,0.85)
setProperty('petals.antialiasing',false)
addLuaSprite('petals')

makeAnimatedLuaSprite('girls','weeb/bgFreaks',-100,190)
addAnimationByPrefix('girls','idle2','BG fangirls glitch',24,true)
scaleObject('girls',6,6)
setScrollFactor('girls',0.9,0.9)
setProperty('girls.antialiasing',false)
addLuaSprite('girls')

makeLuaSprite('lay','weeb/Vin',-325,-175)
setObjectCamera('lay','hud')
setProperty('lay.visible',false)
scaleObject('lay',0.8,0.8)
addLuaSprite('lay')
end
end
function onStartCountdown()
playSound('ANGRY_TEXT_BOX',1)
return Function_Countinue
end