function onCreate()
makeAnimatedLuaSprite('bg','weeb/school/schoolGlitch/animatedEvilSchool',-850,-1000)
addAnimationByPrefix('bg','idle','background 2 instance 1',24,true)
scaleObject('bg',6,6)
setScrollFactor('bg',0.8,0.9)
setProperty('bg.antialiasing',false)
addLuaSprite('bg')

makeAnimatedLuaSprite('bg2','weeb/school/schoolGlitch/animatedGlitchSchool',-850,-1000)
addAnimationByPrefix('bg2','idle','background 2',24,true)
scaleObject('bg2',6,6)
setScrollFactor('bg2',0.8,0.9)
setProperty('bg2.visible',false)
setProperty('bg2.antialiasing',false)
addLuaSprite('bg2')

makeAnimatedLuaSprite('bg3','weeb/school/schoolGlitch/animatedGlitchSchool',-850,-1050)
addAnimationByPrefix('bg3','idle','background 2',24,true)
scaleObject('bg3',6,6)
setScrollFactor('bg3',0.8,0.9)
setProperty('bg3.visible',false)
setProperty('bg3.antialiasing',false)
addLuaSprite('bg3')

makeLuaSprite('skyg','weeb/school/weebSkyGlitch2',0,0)
scaleObject('skyg',6,6)
setProperty('skyg.antialiasing',false)
setProperty('skyg.visible',false)
setScrollFactor('skyg',0.1,0.1)
addLuaSprite('skyg')

makeLuaSprite('sky2','weeb/school/schoolD3/weebSkyFallen3',0,0)
scaleObject('sky2',6,6)
setProperty('sky2.antialiasing',false)
setScrollFactor('sky2',0.1,0.1)
setProperty('sky2.visible',false)
addLuaSprite('sky2')

makeLuaSprite('school2','weeb/school/schoolD3/weebSchoolFallen3',-200,0)
scaleObject('school2',6,6)
setProperty('school2.antialiasing',false)
setProperty('school2.visible',false)
setScrollFactor('school2',0.6,0.9)
addLuaSprite('school2')

makeLuaSprite('schoolg','weeb/school/weebSchoolGlitch2',-200,0)
scaleObject('schoolg',6,6)
setProperty('schoolg.antialiasing',false)
setProperty('schoolg.visible',false)
setScrollFactor('schoolg',0.6,0.9)
addLuaSprite('schoolg')

makeLuaSprite('street2','weeb/school/schoolD3/weebStreetFallen3',-200,0)
scaleObject('street2',6,6)
setProperty('street2.antialiasing',false)
setScrollFactor('street2',0.95,0.95)
setProperty('street2.visible',false)
addLuaSprite('street2')

makeLuaSprite('streetg','weeb/school/weebStreetGlitch2',-200,0)
scaleObject('streetg',6,6)
setProperty('streetg.antialiasing',false)
setScrollFactor('streetg',0.95,0.95)
setProperty('streetg.visible',false)
addLuaSprite('streetg')

makeLuaSprite('bgtree2','weeb/school/schoolD3/weebTreesBackFallen3',-150,50)
scaleObject('bgtree2',5.5,5.5)
setProperty('bgtree2.antialiasing',false)
setScrollFactor('bgtree2',0.9,0.9)
setProperty('bgtree2.visible',false)
addLuaSprite('bgtree2')

makeLuaSprite('bgtreeg','weeb/school/weebTreesBackGlitch2',-150,50)
scaleObject('bgtreeg',5.5,5.5)
setProperty('bgtreeg.antialiasing',false)
setScrollFactor('bgtreeg',0.9,0.9)
setProperty('bgtreeg.visible',false)
addLuaSprite('bgtreeg')

makeAnimatedLuaSprite('trees2','weeb/school/schoolD3/weebTreesFallen3',-780,-1000)
addAnimationByPrefix('trees2','idle','trees',12,true)
scaleObject('trees2',6,6)
setScrollFactor('trees2',0.85,0.85)
setProperty('trees2.antialiasing',false)
setProperty('trees2.visible',false)
addLuaSprite('trees2')

makeAnimatedLuaSprite('treesg','weeb/school/weebTreesGlitch2',-780,-1000)
addAnimationByPrefix('treesg','idle','trees',12,true)
scaleObject('treesg',6,6)
setScrollFactor('treesg',0.85,0.85)
setProperty('treesg.antialiasing',false)
setProperty('treesg.visible',false)
addLuaSprite('treesg')

makeAnimatedLuaSprite('petals','weeb/school/schoolD3/petals',-200,-40)
addAnimationByPrefix('petals','idle','PETALS ALL',24,true)
scaleObject('petals',6,6)
setScrollFactor('petals',0.85,0.85)
setProperty('petals.visible',false)
setProperty('petals.antialiasing',false)
addLuaSprite('petals')

makeLuaSprite('lay','weeb/overlayDepressed',0,0)
setObjectCamera('lay','hud')
addLuaSprite('lay')

makeLuaSprite('lay2','weeb/VinWhite',-325,-175)
setObjectCamera('lay2','hud')
scaleObject('lay2',0.8,0.8)
setProperty('lay2.visible',false)
addLuaSprite('lay2')

     makeLuaSprite('flashw', '', -200, -200);
        makeGraphic('flashw',5000,5000,'ffffff')
	      addLuaSprite('flashw', true);
	      setProperty('flashw.scale.x',5)
	      setProperty('flashw.scale.y',5)
	      setProperty('flashw.alpha',0)

addLuaScript('scripts/extra_scripts/createShader')

callScript('scripts/extra_scripts/createShader','createShader',{'grey','grey'})
end