function onCreate()

makeLuaSprite('sky','stage_assets/weeb/school/weebSky',0,0)
scaleObject('sky',6,6)
setProperty('sky.antialiasing',false)
setScrollFactor('sky',0.1,0.1)
addLuaSprite('sky')

makeLuaSprite('skyg','stage_assets/weeb/school/weebSkyGlitch',0,0)
scaleObject('skyg',6,6)
setProperty('skyg.antialiasing',false)
setProperty('skyg.visible',false)
setScrollFactor('skyg',0.1,0.1)
addLuaSprite('skyg')

makeLuaSprite('skyg2','stage_assets/weeb/school/scarySchool/weebSkyEvil',0,0)
scaleObject('skyg2',6,6)
setProperty('skyg2.antialiasing',false)
setProperty('skyg2.visible',false)
setScrollFactor('skyg2',0.1,0.1)
addLuaSprite('skyg2')

makeLuaSprite('school','stage_assets/weeb/school/weebSchool',-200,0)
scaleObject('school',6,6)
setProperty('school.antialiasing',false)
setScrollFactor('school',0.6,0.9)
addLuaSprite('school')

makeLuaSprite('schoolg','stage_assets/weeb/school/weebSchoolGlitch',-200,0)
scaleObject('schoolg',6,6)
setProperty('schoolg.antialiasing',false)
setProperty('schoolg.visible',false)
setScrollFactor('schoolg',0.6,0.9)
addLuaSprite('schoolg')

makeLuaSprite('street','stage_assets/weeb/school/weebStreet',-200,0)
scaleObject('street',6,6)
setProperty('street.antialiasing',false)
setScrollFactor('street',0.95,0.95)
addLuaSprite('street')

makeLuaSprite('streetg','stage_assets/weeb/school/weebStreetGlitch',-200,0)
scaleObject('streetg',6,6)
setProperty('streetg.antialiasing',false)
setScrollFactor('streetg',0.95,0.95)
setProperty('streetg.visible',false)
addLuaSprite('streetg')

makeLuaSprite('bgtree','stage_assets/weeb/school/weebTreesBack',-200,-30)
scaleObject('bgtree',6,6)
setProperty('bgtree.antialiasing',false)
setScrollFactor('bgtree',0.9,0.9)
addLuaSprite('bgtree')

makeLuaSprite('bgtreeg','stage_assets/weeb/school/weebTreesBackGlitch',-200,-30)
scaleObject('bgtreeg',6,6)
setProperty('bgtreeg.antialiasing',false)
setScrollFactor('bgtreeg',0.9,0.9)
setProperty('bgtreeg.visible',false)
addLuaSprite('bgtreeg')

makeAnimatedLuaSprite('trees','stage_assets/weeb/school/weebTrees',-780,-1100)
addAnimationByPrefix('trees','idle','trees',12,true)
scaleObject('trees',6,6)
setScrollFactor('trees',0.85,0.85)
setProperty('trees.antialiasing',false)
addLuaSprite('trees')

makeAnimatedLuaSprite('treesg','stage_assets/weeb/school/weebTreesGlitch',-780,-1100)
addAnimationByPrefix('treesg','idle','trees',12,true)
scaleObject('treesg',6,6)
setScrollFactor('treesg',0.85,0.85)
setProperty('treesg.antialiasing',false)
setProperty('treesg.visible',false)
addLuaSprite('treesg')

makeAnimatedLuaSprite('petals','stage_assets/weeb/school/petals',-200,-40)
addAnimationByPrefix('petals','idle','PETALS ALL',24,true)
scaleObject('petals',6,6)
setScrollFactor('petals',0.85,0.85)
setProperty('petals.antialiasing',false)
addLuaSprite('petals')

makeAnimatedLuaSprite('girls','stage_assets/weeb/bgFreaks',-100,190)
addAnimationByPrefix('girls','idle','BG fangirls ghoul',24,true)
addAnimationByPrefix('girls','idle2','BG fangirls glitch',24,true)
addAnimationByPrefix('girls','idle3','BG girls group',24,true)
scaleObject('girls',6,6)
setScrollFactor('girls',0.9,0.9)
setProperty('girls.antialiasing',false)
addLuaSprite('girls')
objectPlayAnimation('girls','idle3')
end
function goodNoteHit(id,dir,type,sus)
    if type == 'Senpai Note' then
    setProperty('treesg.visible',true)
    setProperty('schoolg.visible',true)
    setProperty('streetg.visible',true)
    setProperty('bgtreeg.visible',true)
    setProperty('skyg.visible',true)
    setProperty('trees.visible',false)
    setProperty('school.visible',false)
    setProperty('street.visible',false)
    setProperty('bgtree.visible',false)
    setProperty('sky.visible',false)
    objectPlayAnimation('girls','idle2')
    end
    if type == 'Senpai Note 2' then
        setProperty('trees.visible',true)
        setProperty('school.visible',true)
        setProperty('street.visible',true)
        setProperty('bgtree.visible',true)
        setProperty('sky.visible',true)
        setProperty('treesg.visible',false)
        setProperty('schoolg.visible',false)
        setProperty('streetg.visible',false)
        setProperty('bgtreeg.visible',false)
        setProperty('skyg.visible',false)
        objectPlayAnimation('girls','idle3')
        end
    end