function onUpdate()
if curStep <= 0 then
makeLuaSprite('sky','stage_assets/weeb/school/schoolD3/weebSkyFallen',0,0)
scaleObject('sky',6,6)
setProperty('sky.antialiasing',false)
setScrollFactor('sky',0.1,0.1)
addLuaSprite('sky')

makeLuaSprite('sky2','stage_assets/weeb/school/schoolD3/weebSkyFallen',0,0)
scaleObject('sky2',6,6)
setProperty('sky2.antialiasing',false)
setScrollFactor('sky2',0.1,0.1)
setProperty('sky2.visible',false)
addLuaSprite('sky2')

makeLuaSprite('school','stage_assets/weeb/school/schoolD3/weebSchoolFallen',-200,0)
scaleObject('school',6,6)
setProperty('school.antialiasing',false)
setScrollFactor('school',0.6,0.9)
addLuaSprite('school')

makeLuaSprite('school2','stage_assets/weeb/school/schoolD3/weebSchoolFallen2',-200,0)
scaleObject('school2',6,6)
setProperty('school2.antialiasing',false)
setProperty('school2.visible',false)
setScrollFactor('school2',0.6,0.9)
addLuaSprite('school2')

makeLuaSprite('street','stage_assets/weeb/school/schoolD3/weebStreetFallen',-200,0)
scaleObject('street',6,6)
setProperty('street.antialiasing',false)
setScrollFactor('street',0.95,0.95)
addLuaSprite('street')

makeLuaSprite('street2','stage_assets/weeb/school/schoolD3/weebStreetFallen2',-200,0)
scaleObject('street2',6,6)
setProperty('street2.antialiasing',false)
setScrollFactor('street2',0.95,0.95)
setProperty('street2.visible',false)
addLuaSprite('street2')

makeLuaSprite('bgtree','stage_assets/weeb/school/schoolD3/weebTreesBackFallen',-150,50)
scaleObject('bgtree',5.5,5.5)
setProperty('bgtree.antialiasing',false)
setScrollFactor('bgtree',0.9,0.9)
addLuaSprite('bgtree')

makeLuaSprite('bgtree2','stage_assets/weeb/school/schoolD3/weebTreesBackFallen2',-150,50)
scaleObject('bgtree2',5.5,5.5)
setProperty('bgtree2.antialiasing',false)
setScrollFactor('bgtree2',0.9,0.9)
setProperty('bgtree2.visible',false)
addLuaSprite('bgtree2')

makeAnimatedLuaSprite('trees','stage_assets/weeb/school/schoolD3/weebTreesFallen',-780,-1000)
addAnimationByPrefix('trees','idle','trees',12,true)
scaleObject('trees',6,6)
setScrollFactor('trees',0.85,0.85)
setProperty('trees.antialiasing',false)
addLuaSprite('trees')

makeAnimatedLuaSprite('trees2','stage_assets/weeb/school/schoolD3/weebTreesFallen2',-780,-1000)
addAnimationByPrefix('trees2','idle','trees',12,true)
scaleObject('trees2',6,6)
setScrollFactor('trees2',0.85,0.85)
setProperty('trees2.antialiasing',false)
setProperty('trees2.visible',false)
addLuaSprite('trees2')

makeAnimatedLuaSprite('petals','stage_assets/weeb/school/schoolD3/petals',-200,-40)
addAnimationByPrefix('petals','idle','PETALS ALL',24,true)
scaleObject('petals',6,6)
setScrollFactor('petals',0.85,0.85)
setProperty('petals.antialiasing',false)
addLuaSprite('petals')

makeAnimatedLuaSprite('bgg2','stage_assets/weeb/school/schoolGlitch/animatedEvilSchool',-850,-1000)
addAnimationByPrefix('bgg2','idle','background 2 instance 1',24,true)
scaleObject('bgg2',6,6)
setScrollFactor('bgg2',0.8,0.9)
setProperty('bgg2.visible',false)
setProperty('bgg2.antialiasing',false)
addLuaSprite('bgg2')

makeLuaSprite('lay','weeb/Vin',-325,-175)
setObjectCamera('lay','hud')
scaleObject('lay',0.8,0.8)
addLuaSprite('lay')

addLuaScript('scripts/extra_scripts/createShader')
addLuaScript('data/short-circuit/script')
callScript('scripts/extra_scripts/createShader','createShader',{'bw','bw'})
end
end
function onStartCountdown()
playSound('ANGRY_TEXT_BOX',1)
return Function_Countinue
end